### ISSUE TITLE
[Unit 5] Workbook page references are duplicates of Unit 4

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#10]
Unit 4 asks students to go to do some work on Page 18. Unit 5 appears to start off by having them do the same work. One of these should be removed.

**Comment by schanzer** [comment]
Arg - the word document I was looking at is out of date. closing.

**Comment by Emmay** [comment]
The beginning of Unit 5 asks students to define their world structure on the computer using the blank game template. They use the work they did on page 18 as a reference, but don't re-write anything in the workbook.

**Comment by schanzer** [comment]
Ah, my bad. Sorry. :P
