### ISSUE TITLE
BS2 Unit 4 : Game Brainstorming, first activity

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#100]
The bullet structure makes no sense here -- some bullets are answers to previous bullets, the questions cover a lot of ground, etc.  Should this perhaps be a workbook activity of some kind?  It just looks haphazard as presented.

Also references to "world" structure without world being code-formatted

**Comment by Emmay** [comment]
Game brainstorming moved to Unit 7, new workbook page to address these concerns.
