### ISSUE TITLE
BS2 Unit 7 : being explicit about the world inputs

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#110]
Unit 7 is the first time I'm seeing the notes suggest that someone just fill in the existing world components, then adapt when writing update-world.  This is a good general approach -- why aren't we being explicit about this earlier, actually promoting it as a step in the design recipe when we do update-world?

**Comment by schanzer** [comment]
@Emmay , I think we should also make this explicit in Unit 3, so that all the `cake` functions do the same thing. Then we can close this issue.

**Comment by Emmay** [comment]
Right now in Unit 3, we have one Cake function that everyone works through together: 
"The moment you write Cake in the function’s Range, you know that you’ll need to call the cake constructor and give it five things: the flavor, color, message, layers, and is-iceCream of that cake. "

I think I should probably change the first part of the example progression to look like:
examples:
change-flavor(cake1, "strawberry") is (cake
                                                              ...flavor....
                                                              ....color...
                                                             ...message...
                                                             ...layers...
                                                           ....is-iceCream...  )

**Comment by schanzer** [comment]
EXACTLY. Do this and then close.
