### ISSUE TITLE
Revisit Party

### ISSUE THREAD

**Issue by Emmay** [bootstrapworld/curr#120]
Blank Data definition Page? Include functions that make Parties?

**Comment by Emmay** [comment]
@schanzer Any further thoughts on this? Having another struct in addition to Coords and Cakes might be useful- right now this is a quick review activity at the beginning of unit 3 where students write the data block and define some Parties. Worth extending into a longer activity where they write functions that make Parties?

**Comment by schanzer** [comment]
Do we have the time for additional struct exercises? I'd actually say let's keep things as they are, and add if we find that a need for it.
