### ISSUE TITLE
Major curriculum change: re-write your BS1 game in Pyret

### ISSUE THREAD

**Issue by Emmay** [bootstrapworld/curr#136]

**Comment by schanzer** [comment]
Related to #139 
This should be the "small capstone" of the BS:2 curriculum, where kids finish by rewriting their games and then iteratively enhancing them.

Starting a brand-new game from scratch should be a supplemental lesson, with modules for side-scrollers, driving games, etc

**Comment by schanzer** [comment]
Now that students write NinjaCat in BS:2, I think we've got this base covered. Closing.
