### ISSUE TITLE
Helper functions for simple updates

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#140]
In the Unit where students write helper functions, we should point out that most of the constructors don't really modify the entire world. This is a great motivation for writing things like...

update-targetX : World Number -> World

...which just produces a new world based on the old one, with just targetX changed. Then students can massively clean up their code using this new helper function.

**Comment by gregory-marton** [comment]
Writing these gets repetitive. I can see the point of writing the first few, for understanding, but why not ask `define-struct` to provide these functions?

**Comment by schanzer** [comment]
I'm still not convinced it's good to even _have_ updating functions. Pedagogically, we're seeing more and more kids who just NEED to write out all the field names the moment they use a constructor, and then go back and make a decision about what to do for each one.

(This is totally in-line with HtDP, once again proving that Matthias and Company have blazed this trail long before we did.)

**Comment by schanzer** [comment]
Let's close this - I'm more convinced than ever that updating functions like this are not a good fit for BS:2
