### ISSUE TITLE
BS1 Game template: Take out SCREENSHOT

### ISSUE THREAD

**Issue by Emmay** [bootstrapworld/curr#142]
This is a cool activity, but it's confusing and more trouble than it's worth for kids and teachers, because it has nothing to do with the game.

**Comment by Emmay** [comment]
New, better idea: Take out SCREENSHOT from the game template, have a separate file with just image definitions and screenshot that students can play around with before the video game, then they can copy their image definitions directly to the video game file afterwards.

**Comment by schanzer** [comment]
This is done as of Fall 2016. Closing.
