### ISSUE TITLE
BS2, Unit 4, animation timing

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#149]
In the "Hollywood Principle" lesson, it refers to updates after five seconds.  "Five seconds" is too long a time -- at that rate, animation would not be smooth.  The actual value is closer to 1/28th of a second (at least from what I recall of the default values in DrRacket).  Change to a number that is well under a second, otherwise the reader might expect to perceive the difference.

**Comment by schanzer** [comment]
Five seconds is the correct length of time for this activity. How could it possibly happen in less than a second?

**Comment by kfisler** [comment]
Maybe I misunderstand the point of the text.  It sounds to me that you are describing the frame rate. If so, five seconds would be too long to yield a smooth/realistic animation.  But if I'm confused, just say so.

**Comment by schanzer** [comment]
This is for kids to act out big-bang.

**Comment by kfisler** [comment]
That is not at all clear from where "five seconds" appears in the notes.  I'd buy this if "five seconds" came up in the activity box about students acting this out.  But the language surrounding this phrase really sounds like you are explaining what the computer does (until you hit this weird reference to "paper" in the middle of the discussion). At the very least, these few paragraphs seem to be switching between the human and computer implementation of big-bang -- it's confusing.

**Comment by schanzer** [comment]
Are you reading the teacher notes?

**Comment by kfisler** [comment]
I wasn't.  The notes should make logical sense with teacher notes off.  I just enabled teacher notes and there is more context there, but that doesn't change the fact that the reference to "five seconds" and "paper" in what appears to be a discussion about the computer is confusing.  

With notes on, it seems even more clear that the baseline notes have leaked content from the teacher presentation.

**Comment by schanzer** [comment]
See changes in 9c8744843655a4bf9f7de368e04d8b1ef8625fcd

**Comment by kfisler** [comment]
Looks fine, sans resolving the Hollywood Principle wording raised in the other open issue (heading back over there next)
