### ISSUE TITLE
[Unit 6] Add supplemental exercise to introduce Ask:

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#15]
There's no room for it in the lesson plan, but I feel like we should least *offer* teachers a chance to introduce or practice using Ask:. How about re-writing red-shape?

**Comment by Emmay** [comment]
Right now red-shape is the review for Unit 7. Does it make more sense to put it in Unit 6, and create another problem for the Unit 7 review?

**Comment by schanzer** [comment]
Definitely.

**Comment by Emmay** [comment]
See the new page 31, strong-password. Here is the code: https://code.pyret.org/editor#share=0B9rKDmABYlJVdkdmZXpJa3daYkU&v=v0.5r1195
