### ISSUE TITLE
How do we produce videos and screenshots of animations

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#159]
Trying to maintain visual consistency here -- unit 3 calls for stills and a video of the sunset animation.  What tools do you typically use to produce these?  Emma: is this something you have time to do, seeing as you know where the solution files are?

(Note that this depends on the previous question about when we bring in the land, as we have to decide which version to animate)

**Comment by Emmay** [comment]
I've never made a gif or video from an animation, and am not sure how, or how much time that would take. @schanzer, any ideas?

**Comment by schanzer** [comment]
I use a screen-recording tool called Camtasia, which can be used a limited number of times for free. I think I've seen Joe post animated gifs to Github for CPO bugs. Will ask him...
