### ISSUE TITLE
[BS:R] Do we already have a diagram of draw-state/next-state interaction?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#160]
Unit 3 references this, and I'd rather be consistent if we already have a picture for this.  Again, also looking for visual consistency.

**Comment by Emmay** [comment]
We don't have one. We have an idea for a slickly-animated video for how a reactor works, but nothing usable at this time.

**Comment by schanzer** [comment]
This is something that would be WELL worth paying a little money for. It's such a critical concept, and it's so hard to teach teachers in a way that will allow them to teach it to their students. It's crying out for some animation! :)

**Comment by schanzer** [comment]
From Joe: "LiceCap. It's ok -- good recording interface, but the gifs it generates haven't always been compatible with everything. They work in slack and github though, which is half the battle"

**Comment by Emmay** [comment]
Keeping this issue open, but removing it from the "Release" milestone, since we'll be coming back to this sometime after CSPdWeek.

**Comment by schanzer** [comment]
Tracked in Remix, on https://github.com/bootstrapworld/curriculum/issues/188
