### ISSUE TITLE
Definition of state is implementation level, not conceptual

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#161]
I was editing unit 3 and about to introduce the idea of the "state" of an animation (leading up to writing the SunsetState data block).  But the glossary has state as a term of implementation (it refers to the value in the reactor), which means we can't cite state as a technical term before we introduce reactors.

Is there another term you are using for the concept of state?  Or should we modify the glossary to show both the conceptual definition and the implementation-level one?

**Comment by Emmay** [comment]
I would go for modifying the glossary to show both definitions.

**Comment by schanzer** [comment]
Proposed alternate definition: _The value of a changing system at any point in time (ie - a stoplight can be in the "red", "yellow" or "green" state). In Pyret, the state of a Reactor is it's current value._

**Comment by Emmay** [comment]
I like the new definition! @kfisler, any objections to me adding to the glossary?
