### ISSUE TITLE
Colorful Sun -- is "helper function" in the glossary?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#165]
Seems like "helper function" should be a glossary term.  

Where in the progression from BS1 into BS2 do we introduce this idea?  Is this the first time the idea of a helper has come up?  If so, we need to stage/scaffold this more explicitly.  Else should refer to the earlier discussion.

**Comment by Emmay** [comment]
It's not currently in the glossary, but I'll add it and scaffold it more in unit 4. How do you like this as a definition: (

"helper function - a way of shortening and simplifying code by writing a smaller function to perform a repetitive task inside a larger function"

**Comment by schanzer** [comment]
I'd offer this as an alternative:

"helper function - a small function that performs frequently-used tasks, and is used from within one or more other functions"
