### ISSUE TITLE
Unit 4 -- optional section -- a followup question on wrapping

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#167]
When I read the optional idea to wrap the sun (good), my first thought as a teacher was to ask: 

"what color will the sun be when it wraps back around?  Will is be red (the last color it had at the bottom) or will it return to being yellow?"  I'd put this with a teacher note that this is an especially good question for students who have programmed with variables and updates (as many would have in scratch, for example).  I think this point is worth working into the wrap-around suggestion.  Maybe elevate wrap to an activity rather than a sentence to make room for this?

**Comment by Emmay** [comment]
Added this as an activity and teacher's note to unit 4.
