### ISSUE TITLE
BS2 index page: how we present the units after #5

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#168]
Am I right that units 6-10 are independent of one another?  

Seems we are better off renaming these units to something other than Unit 6, Unit 7, instead naming them things like "Game Feature: Moving Between Levels".  Is there a reason not to do that?

I checked the scribble sources, and it doesn't seem too hard to make this change (I'd have to edit main.scrbl, but the code is already set up to do these sorts of unnumbered units as we do for Supplemental Lessons)

**Comment by Emmay** [comment]
Agreed we need to change the names. After unit 5 we have different "tracks", and the ones we have now (scoring and levels, Pong) were just put into the unit folders for convenience. Once we agree on a naming convention and the scribble source gets changed, we can change the track names.
