### ISSUE TITLE
Should reactors have more descriptive names than "r"

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#171]
Part of the point of using reactors is that we can have multiple ones in the same file.  But that would only make sense if the name of the reactor were somehow descriptive.

I'm not saying we should necessarily show multiple reactors, but I do think we should set up better naming habits from the start.  For example, we could name the sunset reactor one of

sunset-r
sunset-anim
sunsetR (though I know Shriram hates CamelCase, I think it makes sense here)

or something else.  But a name that's meant to be common across all problems defeats the purpose.

**Comment by Emmay** [comment]
Not a bad idea. This just requires going in and re-naming the reactor in all the unit and starter files, which I can work on next week. I like [name]-r.

**Comment by kfisler** [comment]
My only concern with sunset-r is that it looks too similar to sunset.r.  For folks coming from Racket, this could be particularly confusing.

Maybe react-sunset or sunset-react is safer?

**Comment by schanzer** [comment]
Strictly a branding issue here, but there's definitely a win in some circles if they see the word "react"

**Comment by kfisler** [comment]
I am using sunset-react in unit3 (which react-sunset rolls better, it is more verb-like, whereas the reactor is more of a noun)

**Comment by Emmay** [comment]
Have you made a new sunset starter file for the unit? I see that the current one still uses r. If not, I can update

**Comment by kfisler** [comment]
No, because I don't own the source links (nor do I know where you are maintaining source links).  If you can update, that would be great, as that would also let me do more proofreading.

**Comment by Emmay** [comment]
Updated. Units 3 and 4 should be all set for more proofreading. I'm editing the links and images for Unit 5 now.
