### ISSUE TITLE
Reactor needs to be a code-mirror keyword

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#172]
Emmanuel: do you remember where we specify the list of keywords?

**Comment by schanzer** [comment]
I believe it's [here](https://github.com/bootstrapworld/curr/blob/bs2-revisions/lib/pyret-mode.js#L26), but Ben is most likely the person to ask if that doesn't work.

**Comment by kfisler** [comment]
that did it.  Closing
