### ISSUE TITLE
Why does the Bootstrap:2 title on the workbook use a different font?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#173]
The title is in Lithios, which isn't a font we've been using.  Mistake?

**Comment by Emmay** [comment]
I think this is because our main "Bootstrap" logo with the lambda is an image, so adding a ":2" next to it onto the cover for BS:2 is tricky. Although Lithos does look like the font for the BS:1 cover, just without the lambda inside the O.
