### ISSUE TITLE
Many bogus workbook page refs in later units (8 and 10, for example)

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#174]
We have references to pages like "110" and "222".  Are these there as a flag to us to fix something, are they just broken, etc?  I'm putting the name-based page indices in, but didn't want to touch these without knowing what was going on with them.

**Comment by Emmay** [comment]
Those are flags for me to put in the correct page numbers once the workbook is complete. Although Units 8 and 10 aren't relevant anymore, and will be replaced with tracks once we have more. (right now only units 6 and 7 are tracks, but I'll be separating Unit 6 into 2 (scoring, levels) and adding another track for distance and collision detection.
