### ISSUE TITLE
Should we refer to data blocks in the language table?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#175]
Updating for unit 3.  We build on what they know about data and constructors, but the current language table isn't really set up to capture this.  Figure out how to integrate, or ignore?

**Comment by schanzer** [comment]
Ignore. Even though it's a called a "language table", it's really more of a "functions and types" table. (We don't add `cond`, `define` or `EXAMPLE` to that table in BS:1, either.)
