### ISSUE TITLE
I could use a sanity check on unit3 time estimates

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#176]
Right now, I have 50 minutes to teach the world model/develop sunset and 30 mins for the data structure exercises.  I sort of made those up, so I'd appreciate opinions on whether these are accurate/reasonable.

**Comment by Emmay** [comment]
This seems alright to me, but I've also been guessing with my time estimates. We won't really know until we try it with teachers/have them teach it themselves.

**Comment by schanzer** [comment]
The second lesson will absolutely take more than 30min. I'd bump them _both_ to 55min, since that's a standard classroom period.
