### ISSUE TITLE
When do we tell them to type in from worksheets?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#178]
I need to add instructions to unit3 telling them to open the sunset starter file and fill in what they wrote on the worksheet.  Do we tell them to type in as they finish each section?  Or do we not say when to do this and leave to the teachers?  What's our convention on when to tell them to edit starter files?

**Comment by Emmay** [comment]
Usually after going through everything on paper, there will be a note in the student section of the lesson plan to open the file and copy x function and its examples into the code. You can decide if it makes more sense to do all at once after everything is complete on paper, or in bits and pieces after each function has been written down.
