### ISSUE TITLE
Unit 1, contracts section, why is commas comment here?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#181]
There's a reminder about commas between arguments in the contracts section of unit 1.  Why isn't this in introduction to Pyret instead?  The worksheet for Racket->Pyret conversion has uses of images, so these functions are already coming up in the previous lesson, and this has nothing to do with contracts.

**Comment by Emmay** [comment]
Not sure, but you're right that this fits better in the previous lesson. I'll fix this!
