### ISSUE TITLE
Unit 2 standards appear too generous -- have these been checked?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#182]
Items like "construct linear, quadratic, and exponential models" don't seem to have any place in here.  Has anyone checked the standards we are putting on these, or are these copy/paste holdovers from somewhere else?

**Comment by Emmay** [comment]
I went through and added the standards a few months ago, but they'll need to be updated once the lessons are stable. (There's also plenty of new lessons without standards, and standards that don't relate to lessons now.) It's on my long-term to do list, but if you find standards that don't belong anymore feel free to take them out.

**Comment by schanzer** [comment]
I've gone through all the units except for Collisions ( @Emmay is working on that) and removed the math standards. I'm pretty sure Collisions actually _should_ keep those standards, so that one can be left alone. @kfisler , let me know if this is closed to your satisfaction?
