### ISSUE TITLE
Can we take the "seating arrangements" out of preparations meta-data?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#186]
This just looks silly, especially for BS2 where teachers have already been through BS1 and have established teaching practices.  Objections to removing this?  It is in multiple units.

**Comment by Emmay** [comment]
SOme of these are holdovers from Citizen Schools, so no problems with removing them. I took out "introduce teaching staff, set expectations..." from unit 1 for this same reason.

**Comment by schanzer** [comment]
Yeah, I say toss them
