### ISSUE TITLE
Unit 4 -- piecewise functions identification

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#187]
At the end of "what to wear", the notes talk about recognizing the need for a piecewise function if there are more things changing than there are domain inputs.  That's fine if the contract/domain is given, but this gives no instruction for situations when users are defining their own functions from scratch.  There, shouldn't the issue be whether one circled datum is dependent on another?

The corresponding teacher note talks about "students defining their own piecewise functions later on", so this is even a situation that we're predicting in the notes.

How should we handle this?

**Comment by Emmay** [comment]
I'm not sure I understand the problem. This is exactly what we tell students in BS:1, and won't all piecewise functions have the dependant variable be something that's not included in the contract? Or are you talking about instances where students write the contract incorrectly?

**Comment by kfisler** [comment]
Yes, all piecewise functions will involve something not in the contract.  But the lesson as currently worded assumes that students have both a contract and a set of circled examples (where the number of inputs differs from the number of circles) in order to recognize a piecewise function.  

If a student is defining a function from scratch, they might not have a contract already -- they may be using examples to figure out what contract they need.  In that case, our current instructions don't apply.  I'm suggesting that the notes should speak to this situation as well.

**Comment by Emmay** [comment]
Ah, I see- yeah, I think the best way would be adding a comment about looking for dependent variables in the examples, in that case.

**Comment by Emmay** [comment]
Fixed
