### ISSUE TITLE
I want to slow down "colorful sun"  unit 4 -- objections?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#188]
I think the colorful sun lesson is going way too fast.  Just look at the second activity -- it is mixing up figuring out which function gets affected with which coordinate is involved with which language construct is required.  This is a significant and valuable point, and we're blasting through it here.

Any objections to my taking a crack at slowing this down and staging/scaffolding it into a few more points and activities?  (will likely happen tomorrow morning).

**Comment by Emmay** [comment]
No objections!

**Comment by kfisler** [comment]
I've pushed the changes to this.  Can someone give a proofread?
