### ISSUE TITLE
Unit 5 description is outside of the overview?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#191]
See image below. The "Students return..." line should be on the top, just as it is for Unit 4.

![image](https://cloud.githubusercontent.com/assets/77126/21596231/6eb7eb24-d106-11e6-9b3a-1e1ef0ecc7e2.png)

**Comment by Emmay** [comment]
That should be part of the @unit-description{}. Is anyone working on this file right now, or can I change it?

**Comment by Emmay** [comment]
I see the problem, there's just some curly braces missing. Won't fix yet, unless no one else has edits pending.

**Comment by schanzer** [comment]
I'm editing the file now, but now that you point it out I see what the issue is. I'll fix it up.
