### ISSUE TITLE
@points are very long

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#192]
I just finished a close reading of Unit 5, and it looks like each `@point{}` is enormous. Points are meant to indicate a single unit of teacher or student activity, and ideally should correspond to a single slide on a slide deck. 

This is low priority, but eventually we'll want to break these points up into smaller ones.

**Comment by jpolitz** [comment]
Is there/should we create a document that describes stuff like this?  A how-to/style guide for writing the curricula and using its infrastructure?

It would be useful for others who want to write Bootstrap-like materials, as well as students who get on board with writing curriculum (e.g. if we have many authors using similar infrastructure to write BS:Physics/BS:Data Science stuff).

**Comment by Emmay** [comment]
This is a good idea, but probably a longer-term project- I'd love for teachers to be able to submit their own BS:2 features, although asking folks to handle the Scribble infrastructure, even with a style guide, might be a tall order.

**Comment by jpolitz** [comment]
I'm thinking more like Sam/Oak/Ben – the broadening team of curriculum writers.  We could just write a single sample file, maybe, with a bunch of comments for what each piece is for – the slide per point rule is a good example.  I took some guesses when I was writing this (and maybe didn't ask enough questions).

**Comment by Emmay** [comment]
Ah, you're right- that makes sense, and I like that format!

**Comment by schanzer** [comment]
@jpolitz Bootstrap:1 is awfully polished in this regard - it's had the most eyes on it for the longest time. I would use that as a model. As far as a style document goes, I think that the fixed cost of doing that might not be worth it while we're still such a small team. Any chance the BS:1 lessons could stand on their own as examples for now?
