### ISSUE TITLE
Collisions unit -- split into Pythagorean lesson and coding lesson?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#194]
Given that some teachers will have already covered the Pythagorean theorem as part of BS1, doesn't it make more sense to split this unit into two lessons, one that reviews the theorem (and is marked as "if needed") while the other applies it to detect distance in Pyret?  As written, we are asking the teachers to do the work of skipping material they might well not need.

**Comment by Emmay** [comment]
Works for me.

**Comment by Emmay** [comment]
Fixed
