### ISSUE TITLE
Why no metadata on the "tracks" units?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#195]
These look odd without any metadata -- why the decision to leave the metadata off of all of these?  Most of the metadata categories still apply, and these are essentially units (they aren't disconnected bits as in the BS1 supplemental lessons)

**Comment by Emmay** [comment]
I'm not sure what you mean by metadata- they do include things like preparation and materials, and I've added prerequisites for the lessons that rely on other features.

**Comment by schanzer** [comment]
Kathi means: why do they look different from the Units? They don't have any unit-level metadata, and therefore don't render to HTML the same way as the others.

**Comment by kfisler** [comment]
More concretely, if you look at the numbered units, they have unit-overview, unit-descr and so on at the top.  Without those, none of the prep, materials, etc get populated at the top of the page.

**Comment by Emmay** [comment]
Ah, I see. What is the unit-level metadata that needs to be added? Is that separate from the Scribble files?

**Comment by schanzer** [comment]
I've added metadata to each of the tracks. @kfisler , let me know if there are other items missing? If not, feel free to close.
