### ISSUE TITLE
Collisions unit -- what does it mean to "handle collisions"?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#196]
There's an activity in this unit that reads:

"Out of the major functions in the game (next-state-tick, draw-state, or next-state-key), which do you think you’ll need to edit to handle collisions?"

I don't see where the notes have defined what behavior should happen on a collision.  Without that, how can someone answer a question about how to handle them (collision could end the game, change the image, reset the state, etc)?  What's the more precise wording of this activity?

(It looks like you might be defining this after the activity -- the dog should move off screen -- is that the behavior?  If so, it needs to be stated before the activity)

**Comment by Emmay** [comment]
Good point- In this lesson, collisions should make the danger or target reset, since scoring is in a different feature. It will change the state of the game (as opposed to just the look) which should tell students to modify next-state-tick.

**Comment by Emmay** [comment]
Fixed
