### ISSUE TITLE
Introduction of "handler" vocab

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#199]
It's in the glossary, but it's only referenced from the teacher notes in Unit 3 and 5. Is this a term we're consciously trying to avoid? If so, we should remove it. If not (my preference), we should formally introduce it in Unit 3, and then use it in the later lessons.

I'm happy to make this change, but I want to check if you've already made a decision about this.

**Comment by Emmay** [comment]
We're not trying to avoid it, which is why we put it in the glossary. I'm fine with making this more explicit.

**Comment by schanzer** [comment]
Fixed by 1b6083b496e5478f2261f0aef4afa8a905a17c05
