### ISSUE TITLE
Add a track on data structs for coords?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#202]
I'm looking at the number of fields in the NinjaCat game struct (scoring unit) and cringing inside.  Data structures should not have this many fields, as a general program-design rule.  I understand why we went with flat data, but the idea of cleaning up data through nested data structures seems like something we should address, if only in an optional track.

I'd like to put this on the medium-term to-do list (not pre-release).

**Comment by Emmay** [comment]
Agreed. There was an optional lesson on nested structures in the previous iteration, so we should be able to adapt it into a full feature.
