### ISSUE TITLE
in Pong, what is return type of hit-wall?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#209]
Activity says to write hit-wall without being clear whether this is returning a boolean or a new state instance.  Naming convention isn't there to help either ...

**Comment by schanzer** [comment]
What's the appropriate naming convention here? `did-hit-wall`? `should-bounce`?

**Comment by jpolitz** [comment]
I would choose `is-hitting-wall` or `is-on-wall`, to use the `is-` convention when possible, and talk about the "present" rather than the past or future, which could be confusing for off-by-one-tick reasoning.
