### ISSUE TITLE
Definition and use of helper function are inconsistent

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#215]
Our glossary definition of a helper says that it is "A small function that contains frequently-used code, which is called from within one or more other functions".  This suggests that common code is in a helper.  But in unit 4, we are using the helper to contain the differences (which sun image to create), not the common part.  The common part stayed in draw-state.

Should we reword to

A small function that handles a specific part of another computation, and gets called from other functions

?

**Comment by schanzer** [comment]
Sorry, I thought I responded to this earlier! I think the new wording is excellent.
