### ISSUE TITLE
Assessment and/or Rubric

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#219]
Should be a "guidance document", like https://docs.google.com/document/d/1uJk66awwVCqJPSTiwMy1FKuYd1FipsShJwCUCq0P7Tw/edit

**Comment by Emmay** [comment]
Grading rubric for a reactor program- what should you, as a teacher, look for when grading a reactor program? What are all the ways a [data definition], [draw-state function], etc. can be written poorly?

**Comment by Emmay** [comment]
Finished and linked on the teacher resources page!
