### ISSUE TITLE
[DS-Unit 2] bring more interactivity/discovery to table intro.

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#223]
Proposal: start with a table (mirrored in the workbook), that has no header row. Let the workbook have space for a header row, but with faint borders so it's not immediately visible. 

Ask a series of questions (e.g. - "How many rows are in this table?", "How many columns are in each row?", "Do all the rows have the same number of columns?", "What is the value in the 3rd column of the second row?", What is the _type_ of the value in the 2nd column of the last tow?", etc....). Then ask them to come up with column names, and fill them in.

THEN explain that tables need header rows, and what they're called.

**Comment by SDooman** [comment]
I'm not sold on having students try to infer the column names just from the contents of the column.

- It's not clear what the values for the `height` column are without the label.   Same problem with the `eye-color`
- This isn't something they'll be asked to do again later in the core curriculum, although I can see the need for students to name columns they find from open data sources on the web (one of the planned supplements).

If we decide to make this change, I think the example table (the classroom) needs to be changed to make the data more "inferrable"

**Comment by schanzer** [comment]
Good points all around. I'm convinced. Closing.
