### ISSUE TITLE
[DS-META] Why does DS use import instead of include?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#225]
`GDS.load-spreadsheet` has a higher cognitive load than `load-spreadsheet()`, and is syntactically closer to other function applications like `num-min()`.

**Comment by SDooman** [comment]
https://github.com/brownplt/pyret-lang/issues/975

As of right now, `include gdrive-sheets` is broken.  As soon as we resolve that issue, I'll change the scaffolded code found [here](https://code.pyret.org/editor#share=0BxJ2mGqPUGt0bnZKcHYxbG5HSG8&v=3a4fb05) to reflect it

**Comment by schanzer** [comment]
Looks like this is fixed, and I see you've updated all the files. Nice!
