### ISSUE TITLE
[DS-Unit 2] Refer back to header row intro when loading a table

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#226]
Related to #223 

When it's time to introduce `load-table:`, you should refer students back to the importance of having a header row. "As you saw at the beginning of the lesson, tables need header rows to describe them! Just as you did in your workbook, you need to come up with a header row for this table in Pyret. The `load-table:` block lets you do just that!"

**Comment by SDooman** [comment]
@schanzer 

As it stands, this information is in the teacher notes, so that teachers can show students if they want to.  Should it be in the regular notes?

**Comment by schanzer** [comment]
Don't the lesson notes already refer to that line of code, by way of explanation? If so, that's good enough. If not, then yes -- go ahead and add this.
