### ISSUE TITLE
[Units 2/3/4] Is it optimal to teach table loading before table manipulation?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#227]
It's always important to balance the # of steps against the reward, and I'm not convinced we have the optimal balance here. The second half of Unit 2 is cognitively and motivationally expensive. since there's a ton of syntax to learn just to load a table and then see it in CPO. A student might ask "Who cares? It's just the same table I saw in Google, only I had to fix 10 syntax errors to see it in CPO!" 

I wonder if it makes sense to start with a program that has these tables pre-loaded, and _not explain the syntax at all_. From there, we can jump straight into discussing categorical and quantitative data. This would make Unit 2 entirely conceptual, with kids answering questions by looking at table printouts in the REPL. I envision interesting activities/games where we try to "trick" students about which kind of data they're seeing (the zip code one is awesome), daring them to tell us which kind of data is in each column. We could give them a series of questions about data, asking them to tell us whether these questions can be answered using quantitative or qualitative data. Then we flip the script, giving them a kind of data and having them come up with questions about it.

Then, in Unit 3, kids experiment with selecting and ordering (as they currently do in Unit 4). 

The point is, I don't see any point to teaching kids how to load a table until it's time for them to go find their own data sources.  By leaving the syntax visible but not explaining it, it's a chance for the advanced kids to fiddle around.

**Comment by shriram** [comment]
​This is a great idea: start with pre-loaded tables so they can just learn
the operations. We can also give them 3-4 different pre-loadeds depending
on which dataset they want to try out.

**Comment by schanzer** [comment]
Sam and I discussed this for about an hour this morning, and identified a lot of other pedagogical optimizations that come from this change.
