### ISSUE TITLE
[Unit 1] - Workbook activity is unclear

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#228]
You ask students to write down what error appears. Some of these errors are quite long - do you really want them to copy all of it? And you haven't left any lines for them to write on. Where should they draw the mini-editor that's in all the errors?

Same beef on Page 2

Page 3 - make this a table, so students know where to write.

**Comment by SDooman** [comment]
these points addressed in PR except for the last one:  The exercise on page 3 should be a table, it just may not be formatted correctly depending on which markdown->PDF renderer is used.  I'm going to switch to either word/pages documents soon.
