### ISSUE TITLE
BS2 Unit1 : shortcut

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#23]
Do you usually refer to defined names as "shortcuts"?  That phrase is being used in a semi-technical way a couple of points above the "contracts" lesson.  I can understand an informal, intuitive description of a definition giving a shortcut, but is that the term we want to use in more definitional contexts?

**Comment by Emmay** [comment]
This is what we use to talk about defining values in BS:1. "Now we have values, and we know how to define shortcuts for them", doesn't seem too technical to me, but is there a better way to re-phrase this?
