### ISSUE TITLE
[DS-META]  Table keywords aren't bolded in @code{} blocks

### ISSUE THREAD

**Issue by SDooman** [bootstrapworld/curr#234]
Need to bold the text in code blocks for each of the following key words:

- load-table
- select
- order
- sieve
- extend
- extract
- using
- from

All we need to do is grab an updated, table-aware copy of the Pyret syntax highlighter from CPO.

**Comment by schanzer** [comment]
Fixed by f21d3737b6d7191cef9996890d29d0a71fdea777
