### ISSUE TITLE
[DS-META]  Add parking lot

### ISSUE THREAD

**Issue by SDooman** [bootstrapworld/curr#240]
This requires quite a bit of work:
 - Update Unit 1 to mention process of "every time you have a question about a data set, and don't know how to answer it YET, write it in the parking lot"
 - Add our prescribed parking lot questions to Units 1 - 9
 - Add parking lot section in back of workbook

**Comment by schanzer** [comment]
This is obviated by the "narrative final project" that is now threaded throughout the course. It essentially provides a parking lot that students add to as they go.
