### ISSUE TITLE
Why is the Reactive/Nested unit called a "Feature"?

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#245]
I think of a feature as something an end-user (or student) could identify in the game play.  Structure Nesting isn't a feature by that definition.  It's more of a "Design" issue.  I'm open to other word choices, but don't think "Feature" makes sense.

**Comment by Emmay** [comment]
"Feature" is the label we decided on (instead of "Track") for the extra activities in Reactive that come after the units. Agreed that nested structures doesn't introduce a new game/animation feature, but it's consistent with the other labels.

**Comment by kfisler** [comment]
My point is that Nested is not conceptually consist with the others, which do introduce features. I think we need a different label for this one, so as not to be misleading.

**Comment by Emmay** [comment]
How about something like "Concept: Nested Structures" or "Going Deeper: Nested Structures", or just "Programming Topic: Nested Structures"? Maybe a little boring, but more descriptive.

**Comment by Emmay** [comment]
Changed to "Going Deeper: Nested Structures"
