### ISSUE TITLE
[DS - Unit 5] We never answer whether or not to play the dice game

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#258]
In the lesson notes...
"Should we play the game?  We haven't answered this question yet.  What do we need to know to figure this out?"

Then we introduce histograms. But we never actually show students that histograms allow us to answer this question!

**Comment by SDooman** [comment]
Addressed [here](https://github.com/bootstrapworld/curr/commit/2a4b29caabaa3a69f887b59240c6e08159a48387)
