### ISSUE TITLE
[DS - Unit 7] Ordering by hand is too long

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#259]
We have students do a lot of by-hand table reproduction, but I don't think it's terribly useful. They understand what ordering is, and I think it's a huge timesuck to have them do. We make them create **3** new tables by hand, and then do a workbook exercise on top of it. Let's cut this down to just one table, which is ideally done in the workbook.

This should cut the time for this section from 25min down to 10 (though honestly, do we even need 10?), and allow us to jump straight into ordering in Pyret. These should be just one section, just like Selecting.

**Comment by SDooman** [comment]
I removed the 3 manual table creation exercises, but kept the workbook the same (creating 2 new tables, each with 4 rows and 3 columns).  Hopefully these tables are small enough that students do the minimum amount of grunt work to see the effect of ordering by a particular column, which is a necessary concept in Ordering.
