### ISSUE TITLE
[DS - Unit 9] - Too much jargon in the UN Exercise

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#260]
Most kids won't know what 'GDP' or 'per-capita' mean. You need to either define these or use more commonplace terms. My preference would be the first option. Either way, this section should have several activities added to it that check for understanding of these definitions, before you have them start the table plan.

**Comment by SDooman** [comment]
@schanzer addressed [here](https://github.com/bootstrapworld/curr/commit/2a4b29caabaa3a69f887b59240c6e08159a48387).  I'm not sure how much more we can add that teachers will strictly adhere to.

**Comment by schanzer** [comment]
LGTN
