### ISSUE TITLE
BS2 syntax coloring

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#28]
Unlike BS1, BS2 doesn't seem to have syntax coloring.  Presume this is something we want, and that fixing this is a Kathi/Emmanuel issue?

**Comment by Emmay** [comment]
Yes. Coloring should be consistent with the Pyret editor students use, which I assume will be code.pyret.org

**Comment by schanzer** [comment]
Fixed in 929095983b69270b99482f19c6ac870320daf68f
