### ISSUE TITLE
[DS] Improve "Are any of the columns unnecessry?" in table plans

### ISSUE THREAD

**Issue by taps3** [bootstrapworld/curr#315]
Are any of the columns unnecessary? This question implies that a select query removes columns as opposed to keeping them. This may be the right question when deciding whether or not a select is needed. However, in the workbook it confuses students when they are first learning to use the select query.

**Comment by schanzer** [comment]
@taps3 , how about the following ideas:

1. - "Do I only want certain columns?"
2. - "Which columns do I need?"
3. - "Which columns are in my output?

I'm leaning towards 2, but "need" is such a loaded word...
