### ISSUE TITLE
Contracts Pages - possible revision

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#318]
Should Contracts Pages include one line for the Name/Domain/Range, and another for example?

**Comment by Emmay** [comment]
We had a teacher in the Reactive workshop ask for resizeable/scaleable contracts page for special ed kids who need more room to write. Putting examples on another line would help with that.

**Comment by schanzer** [comment]
Tracked in Remix, on https://github.com/bootstrapworld/curriculum/issues/189
