### ISSUE TITLE
[DS] Measures of variation

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#348]
Could potentially be added to Unit 4, or perhaps given its own Unit. 

Discuss Range, Quartiles, Interquartile Range, and Standard Deviation. If Box-and-Whisker plots are implemented, this _definitely_ needs its own unit.

**Comment by schanzer** [comment]
This stuff is up on http://www.bootstrapworld.org/materials/spring2018/courses/data-science/english/units/unit5/index.html ... we'll see if this flies, or if we need to break it up

**Comment by blerner** [comment]
typo: "The box plot (a.k.a. box and whisker diagram) is **away** of displaying"

**Comment by blerner** [comment]
awkward definition: "quartile: Each of four equal groups into which a population can be divided according to the distribution of values of a particular variable"  "Equal" according to what metric?  "Equal size" (ambiguous), "equal population size" (correct), "equal range" (incorrect)?

**Comment by blerner** [comment]
typo: "It’s important to find ways to talk about lots of data without having to **handover**"

**Comment by sorawee** [comment]
@schanzer (just make sure that you have seen this)

**Comment by sorawee** [comment]
@schanzer Please note that I use method 1 in the Wikipedia article to compute, but there are other methods to use as well (https://en.wikipedia.org/wiki/Quartile#Method_1). If you wish to use something else, please let me know.

Also, FYI, using method 1 means that quartiles for a one element list can't be computed.

**Comment by schanzer** [comment]
@blerner thanks for the edits - I threw this lesson up yesterday because I urgently needed to have _something_. I'm pushing a revision later tonight that includes these fixes, and a lot of other structural improvements.

@sorawee Method 1 is perfect. Thanks!
