### ISSUE TITLE
Ascending syntax error

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/curr#350]
We probably might want to avoid using `ascending` as a parameter name in DS Unit 3. It's a Pyret keyword and can't be used as a variable name.

**Comment by schanzer** [comment]
It's used as a parameter name in the docs https://www.pyret.org/docs/latest/tables.html#%28part._tables_.Table_order-by%29

**Comment by sorawee** [comment]
The doc is wrong then!

**Comment by schanzer** [comment]
Fixed by 1da19751345da97775e47f7ab55274e8a15d5363. Also updated the pyret docs
