### ISSUE TITLE
Workbook solutions should include completed contracts page

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#369]

**Comment by Emmay** [comment]
Looks like we already have a complete contracts page, at curr/courses/algebra/resources/workbook/langs/en-us/pages/Contracts-Sols.pdf
 
Not sure what work has to be done to integrate this into the workbook solutions file in teacher resources. (If it's just a matter of switching out some PDF pages, let me know and I'll do that.)

**Comment by schanzer** [comment]
This is now completed on Remix.
