### ISSUE TITLE
Unit 7 warmup qs/answers differ

### ISSUE THREAD

**Issue by jpolitz** [bootstrapworld/curr#377]
The answers in the Unit 7 warmup activity differ from the questions:

https://docs.google.com/document/d/1k67XlYWkHefd4APynvwSnPKRaSTeOvGD7_lRbI8hHrg/edit
https://docs.google.com/document/d/1BhTRRD6Q-U3_IluazP0X8gh7Sb_LIPP1ur7QjIIiks8/edit

There are also some typos in the answers that aren't in the questions (its vs it's).

Let me know if this isn't the right place to report this!

**Comment by schanzer** [comment]
Fixed. Thanks!!
