### ISSUE TITLE
Consider rewording "Consumes" in purpose statements

### ISSUE THREAD

**Issue by blerner** [bootstrapworld/curr#383]
Especially for the DS animals example dataset, "Consumes an `Animal` and ..." is rather carnivorous!  Also, less whimsically, part of the point of the DS curriculum is that the original data is *not* consumed-as-in-destroyed, but still exists after transformations are applied.  Possible suggested replacement is "Takes in..."

**Comment by schanzer** [comment]
I'm not opposed to "takes in", but this is the terminology we got from HtDP, and I chose this out of a desire for consistency.

**Comment by schanzer** [comment]
After thinking about this for a long time, I'm closing as #wontfix - consistency across curricula is just too worthwhile, especially since I'm leaning towards having all BS:DS helper functions phrased as "consumes a _row_ ..."
