### ISSUE TITLE
[DS] Person.likes() is a disaster

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#387]
This workbook page needs to be completely reworked, or just removed. We wasted 15m on it, and it only made things more confusing.

**Comment by jpolitz** [comment]
FWIW, I didn't do Person.likes in San Diego (mostly just for time). Folks did a fine job with methods, _but_ they had already done all of Pyret algebra, _and_ they mostly just followed the table plans which make method use easy.

With those caveats mentioned, I introduced methods as a new way of doing function-like operations, with a special signature, _just_ using the table methods, and folks made progress.

**Comment by schanzer** [comment]
Fixed by 9b48963
