### ISSUE TITLE
[DS] "Hot streak" examples

### ISSUE THREAD

**Issue by blerner** [bootstrapworld/curr#397]
I ran across an article a few weeks ago, and mentioned this to Shriram.  It's the potential basis for some interesting questions:

Suppose you extended the current Movies spreadsheet with a column for the movie's director.  Next, suppose you had three data sets, all of the same Movies schema: one of them is "all movies of a given decade" (maybe filtered down to a single genre, for manageability's sake); one is "all movies of a given studio"; and one is "all movies of a given director".  The initial question is "Did any director go on a 'hot streak' and have a bunch of hit movies all in a row?"  (Simple data inspection)  The second question is, "*which* of the three datasets would actually answer that question?"  (Understanding something about the completeness of the dataset)  The final prompt is, "For each of the other two datasets, ask a question that could be answered by this dataset."

**Comment by schanzer** [comment]
This is _extremely_ cool!

**Comment by schanzer** [comment]
Tracked on Remix, in https://github.com/bootstrapworld/curriculum/issues/155
