### ISSUE TITLE
Some text in Workbook is generated from a CSS file, which isn't abstracted over multiple langs(Spanish Translation)

### ISSUE THREAD

**Issue by edcamposjr22** [bootstrapworld/curr#398]
Some text in Workbook is generated from a CSS file, which currently isn’t abstracted over multiple languages.  I've edited the Open Office doc and completely translated that but there are some of the Design Recipe pages that do not get translated when I run the build. 

I've attached the file.
[workbook.pdf](https://github.com/bootstrapworld/curr/files/2233010/workbook.pdf)

**Comment by schanzer** [comment]
Fixed in new repo
