### ISSUE TITLE
Workbook pages fail to be scribbled again when changing solutions mode

### ISSUE THREAD

**Issue by doshiro** [bootstrapworld/curr#408]
On new-master, when running
`racket build-workbook.rkt --solutions`
followed by
`racket build-workbook.rkt`

the resultant student workbooks have the solutions for the pages that come from the .scrbl files in the `courses/*/resources/workbook/langs/*/pages` directory. This applies specifically to courses with .scrbl pages, including algebra and algebra-pyret.

**Comment by schanzer** [comment]
@doshiro , this should be resolved with @ds26gte 's new code. Can you confirm?

**Comment by doshiro** [comment]
@schanzer Yes, this fixes the issue. Feel free to close it. Thanks again, @ds26gte !
