### ISSUE TITLE
BS2 Unit 2 : Introducing Structures

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#41]
Rather than talk of functions returning "things" and and combining "things", why aren't you reinforcing the term/concept "values"?

The sentence "thankfully, pyret has a way ..." suggests that this is unique to Pyret, rather than a fundamental concept of programming (and math, which talks of coordinates as single entities!).  Perhaps expand this out to a couple of sentences, something like "this problem arises frequently in both programming and math: we need to treat multiple values as a single, more complex value.  We'll return to this throughout the course.  For now, we simply show you how to create a <data structure> that combines two numbers into a single <coordinate>."

Open to other suggestions on the wording -- this is just a sense of what I'm thinking here.

**Comment by Emmay** [comment]
This was originally written as "Pyret- like many other languages- has a way..." Emmanuel and I took it out because it might be confusing to mention other languages when students are just working with Pyret.

**Comment by kfisler** [comment]
What if we moved the "this goes beyond Pyret" thought to a sentence after the one that refers just to Pyret? I agree it could be too much in the same sentence.

**Comment by schanzer** [comment]
Let's go through these issues tomorrow in person?

**Comment by Emmay** [comment]
Sure- in the meantime I'll work on fixing any typos/quick-fix issues that come up, but we should discuss some of these tomorrow.

**Comment by kfisler** [comment]
Yes, I'm trying to crank through today so we can discuss any more-than-simple-fix stuff in person tomorrow.  Let's assume that anything left open tomorrow needs discussion

**Comment by Emmay** [comment]
Data structure in vocab tags in conclusion and teacher's notes
