### ISSUE TITLE
BS2 Unit 2 : Intro structures -- how to read the defn

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#43]
I don't see anything in the notes that explains how to read the data struct definition in the Pyret file.  We're assuming that people will piece it together.  Might need to be more explicit.

**Comment by Emmay** [comment]
The last section 'Defining data" is supposed to explain this. Is that section not explicit enough?

**Comment by kfisler** [comment]
The problem is that the mention of coord earlier in the lesson says just enough to suggest that the reader should have been able to understand that definition (ie, "for now, the important thing that this code tells you" -- that invites me to read the code so I understand where this "tells" is coming from).

Deferring it is fine.  In that case, be more explicit about it earlier.  Don't tell them to scroll to the Coord part (they'll think they need to read it).  Instead, tell them that you've set up a definition (which is at the top of the file, but you'll go through how to read it at the end of the unit), and just give them the contract  of the constructor without referring back to the code.

**Comment by kfisler** [comment]
In similar spirit, the "it's really easy to make this car struct" comment after the Autobody activity invites people to study that code, when you are trying to defer that.  Remind them that you will come back to that later, so you can focus on making individual cars for now.
