### ISSUE TITLE
Dangling reference in Bootstrap:Algebra Unit 2

### ISSUE THREAD

**Issue by rjmh** [bootstrapworld/curr#434]
On bootstrapworld.org, the first task in Unit 2 of Bootstrap:Algebra is "Circles of Evaluation Review"

This refers to Page 22 of the workbook. Clicking the link and turning to page 22 doesn't appear to be relevant. But page 7 of the workbook contains "Circles Competition" which fits the description in the Unit, so maybe the reference should be to page 7 instead.

However, page 7 is described in the workbook as a 5 minute activity, while "Circles of Evaluation Review" is described in the unit as a 30 minute activity.

**Comment by schanzer** [comment]
Thanks for reporting this, @rjmh !

1) I'm not seeing the Page 22 reference. Are you sure you're looking at the most recent version of the materials?
2) While the activity on Page 7 is designed to take relatively little time, the _discussion_ of that activity in a classroom can easily take a while. We wanted to build in a reasonable estimate for teachers, as a way of letting them know we've considered leaving room for these discussions.
