### ISSUE TITLE
[DS] Contracts aren't enough

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#446]
Ever since we switched to method syntax (where column names are specified by string), we've lost some of the utility of contracts. Functions and methods all consume _strings that refer to columns_, which means seeing "`String`" in the Domain doesn't provide as much of a hint as it does in our other curricula.

I think we need to re-work the contracts pages for DS, so that every function/method has _two_ lines: one for the contract and another providing an example

**Comment by blerner** [comment]
We have a similar issue in BS:Physics, where roughly all the contracts are `Number, Number, Number, blahblahbla Number -> Number`  The physics folks have a variant on the DR worksheet (not the contracts page, yet) where the next line includes the *physical units* for each number, aka the interpretation for each parameter.

**Comment by schanzer** [comment]
Out of curiosity, why aren’t you using the new and improved contract syntax for this? It certainly got us part of the way they in data science, and Iwill admit I’m a little surprised it wasn’t enough to get us the rest of the way. 

If you’re in the same boat, perhaps we should revisit whether the extra syntax and grammar is worth it

**Comment by jpolitz** [comment]
The units provide more information than just the name, unless the name
was e.g. height-in-meters, velocity-in-mps, etc. So there's real value
in writing it separately.

There's also a bit of inertia; they started with stock DR worksheets,
so they've kept using the stock DR, and it is working for them with
the addition of units, so it's stayed that way.

**Comment by schanzer** [comment]
Ah, that makes a lot of sense.

**Comment by schanzer** [comment]
This is essentially a dupe of #318 . Closing
