### ISSUE TITLE
BS2 Unit2 : activity after "used a new function: car"

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#59]
Here again I feel like we're dancing around order-of-presentation issues.  Once people are actually writing their own structs, they can look up the domain types and number of args from the structure definition.  But you haven't covered that, so their only "valid" source of this information is the example.  If you want them to do this activity from the example, say so explicitly.

I really see this in the teacher's notes -- you are talking people through calling the constructor consistently with the definition, but you haven't yet talked about how to read the definition.  This is going to confuse teachers.

I think you need to rework this section slightly: mention that readers are using a function called "car" to create cars.  Have students create cars, type them in, draw them, etc.  Then go back and do the contract.  First extrapolate from the examples, then say "to really see this, we should understand the Pyret code that creates the car data structure".  Then put all of the "defining data" material before the "dot accessors" material.  I just don't think you can talk through contracts and calling constructors with the correct arguments and the like without teaching someone how to read the definitions.

Definitely one for the in-person discussion.

**Comment by Emmay** [comment]
"Based on the examples of Cars you just wrote, what is car 's domain, range.... etc.
