### ISSUE TITLE
BS2 Unit 2 : last activity in "defining data" lesson

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#61]
Refers to workbook page 14, but that page is a DR exercise -- page reference seems incorrect.

**Comment by Emmay** [comment]
Use the new version of the workbook in curr/courses/bs2/resources/workbook, not the PDF linked in the lessons, which is not the newest version.

**Comment by kfisler** [comment]
I'm directly in the StudentWorkbook.doc file in the directory you mentioned ... looked like the doc was current, but not the PDF

**Comment by Emmay** [comment]
That's the one. You're right, page numbers aren't consistent. I'm not worrying about that right now because the workbook will be changing in the next few weeks. Before July 6th I need to go back and change all the page #s and re-link all the source files.
