### ISSUE TITLE
[Unit 3] Students are asked to write struct-specific info in the contracts page?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curr#7]
Students are asked to write the constructor and dot-accessors for the Party struct in their contracts page, even though Party is not part of the language. 

1) This is not the right place for it. Shouldn't it be page 14, where students fill out the data definition?
2) What is the contract for a dot-accessor? I thought we weren't calling them functions, so they shouldn't have a contract.

Proposal: come up with a single-page template for Data Definitions, and give students practice filling it out in Unit 3 for both Party and Car. This template should include the data definition, the contract for the constructor, a place for students to write an example that defines a variable of that type, and (possibly) a list of dot-accessors using that definition. See below:

*#*a Party is a location, theme, and number of guests
data Party:
  | party(location::String, theme::String, guests::Number)
end

To make an example of this structure, I would write....

var party1 = ________________________________________

To access fields of the structure, I would write...

_________________________
_________________________
_________________________

This template can be used over and over, for Cars, Worlds, etc.

**Comment by Emmay** [comment]
Are you suggesting that we give students the data definition for parties and cars on this page, or give them the space to write them down themselves (like it is now)?

**Comment by schanzer** [comment]
Kids still fill it out themselves, but give each structure it's own page, and make sure you're asking the same questions about all of them.  By the time kids reach the (current) world-definition page, it should be the third time they've gone through the same steps.

**Comment by Emmay** [comment]
See the current page 12. I can fit these for both Party and Car on one page, do you think that works or is one page each absolutely necessary? I'll repeat the same pattern for their world structure later on.

**Comment by Emmay** [comment]
Make pg. 12 and 18 look the same, w/ 2 examples of each structure
