### ISSUE TITLE
* BS2 Unit 3 : "changing" language in Autobody shop

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#70]
It's dangerous to talk about "changing" the cars, because it suggests mutation rather than functions.  This is a tricky, tricky issue wording wise.  But especially if we plan to have BS2 appeal to teachers with some CS experience, then we have to write very carefully around "changing" since that isn't what your functions are doing.

This should stay on the list for larger-group discussion.

**Comment by Emmay** [comment]
Teacher notes: Does not give back the same value, it creates a new car with different specs. 
consumes car, produces an identical car where the paint color was changed to the given color
The car we get back must have the same model, hp, value, etc. but one thing is different than the car we started with: the color!
