### ISSUE TITLE
BS2 Unit 3 : Autobody shop , activity that justifies using "purple" directly 

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#75]
The third bullet basically says to use "purple" because it's an argument to the function.  We should use "purple" because the purpose statement says to, not because it's an input and has to show up somewhere.

**Comment by Emmay** [comment]
This is in the example, so isn't it OK to say that we use the specific string given to the function here?

**Comment by kfisler** [comment]
As written, it looks as if you are using the string given to the function because there was _a_ string given, not because the purpose says to use the given color string as the new car color.  I think you just need an extra phrase in here, along the lines of "remember that paint-job takes as input the desired color of the returned car; in this example, that input is "purple" so we use "purple" as the color."

**Comment by Emmay** [comment]
"According to the purpose statement...."
