### ISSUE TITLE
BS2 Unit 4 : just after activity to edit car with sunroof

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#80]
I see the phrase "instances of that structure", but I don't believe I've seen the "instances" term used before (sorry if I missed it).  We do need to be using a term for this, but make sure it has been introduced and emphasized properly up to this point.

**Comment by Emmay** [comment]
Unit 2 defining data: You make instances of structs more often than you would make new data structure.

You've worked with 2 data structures - coords and cars, you've made many examples, or instances of these structures, there's a difference btw structures and their instances. 

Instance glossary term
