### ISSUE TITLE
BS2 Unit 4 : explaining big bang and the World model

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#87]
This is an area where I think you'd be better off not trying to motivate the reader through the pieces of big-bang, but instead coming out and being direct about how an animation gets generated.  The idea that you have a sequence of frames, the elements update frame to frame, while we draw each frame before updating for the next.  This lets you motivate that you need two functions (update and draw), a place to hold all the info (world), and a way to tie together an update and draw into a single animation (big bang).  With that high-level model in hand, a reader can then look at the individual pieces without losing the forest for the trees.

I see some of this is in the teacher notes, but I think we can do a bit better explaining it to the teachers so they can explain to the kids.  Ideally, we need the picture showing a sequence of frames and the use of update/draw world around each frame

**Comment by schanzer** [comment]
@kfisler, is the recent commit what you had in mind?

**Comment by schanzer** [comment]
Sorry to bug you @kfisler , but we need to finalize by Friday (6/24).

**Comment by kfisler** [comment]
Reading the new "Hollywood Principle" lesson from start to finish.  Overall, it looks good.  But ...

A ways down, it says "In programming, this is called the "Hollywood Principle," and it is exactly how we’re going to make the animation work in our programs."

No -- this principle of coordination is not the Hollywood Principle.  The accurate programming term is the "controller".  The "Hollywood Principle" is a term that Shriram (maybe Matthias) uses to refer to decomposing an animation around the filmstrip idea.  

if you want to explain "Hollywood Principle" (and I'm not saying you have to), it would be that we can break animation down into separate functions for draw and next, just as in a filmstrip.  It's a clean way to think about creating an animation, assuming a controller that coordinates the work of those two functions.

**Comment by schanzer** [comment]
It's also a real term used in programming: http://matthewtmead.com/blog/hollywood-principle-dont-call-us-well-call-you-4/

Seems loosely appropriate here, no? If it's not, then let's get rid of the term altogether, since it's already a reserved principle and we're nervous enough about appropriating things like that (e.g. - event-based v. event-driven programming)

**Comment by kfisler** [comment]
I've never heard that term applied to callback-style programming, so I suspect it isn't all that common.

Our (Shriram and my) original use of the term for BS2 referred to something entirely different: the idea that any output that appears continuous (here, the animation) is actually created in a computer through many small discrete updates, each of which is displayed in quick succession.  This is actually an important CS principle that (a) kids at this level can appreciate (unlike callbacks), and (b) that we are in a unique position to present given our programming model.  Here, Hollywood refers to movies, not being brushed off by agents.

It is worth calling this out, perhaps as a separate point towards the end of the lesson (at which point you can use the term "Hollywood Principle" to tie into the lesson title -- it is catchy).  It is certainly something we should be building into our CS assessments as we develop them, and hence something that our notes should be making explicit.
