### ISSUE TITLE
BS2 Unit 4 : activity to add coinX to the world structure

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#93]
This activity feels like it isn't really an activity.  You ask questions and immediately have to give answers.  Other activities seem more things you could send students off to do.  This feels like lesson that is getting written as an activity (at least the first three bullets).  Again, this feels like a very fast presentation that is masking a careful set of questions to ask (almost like steps in the DR, but the "steps" are obscured by presentation here).

**Comment by Emmay** [comment]
Pretty sure our re-write awhile back addressed this. This is the first lesson students are seeing big-bang, and they'll be re-writing code to have animations use a world structure as opposed to just a number. It's not expected students will be totally comfortable with this on their own, rather that a teacher would be walking them through the "extending the world" activities. Take a look and see if the current wording is still too fast.

**Comment by kfisler** [comment]
Seems fine now
