### ISSUE TITLE
BS2 Unit 4 : search and check that world is code-formatted everywhere

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#94]
Seeing lots of instances where it isn't throughout the lesson

**Comment by Emmay** [comment]
I think what I've been doing is using the code tag when talking about the world constructor function, but not when talking about the World data structure. Do you think having this formatting is OK, or should both be in code tags?

**Comment by kfisler** [comment]
Either is fine as long as we're consistent
