### ISSUE TITLE
BS2 Unit 4 : two points from the end of the Extending the World lesson

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curr#96]
"the moment you write world, your instincts should kick in right away :every world contains a dogX and a coinX, so you can write them down automatically" -- but isn't the point that they have to think about what the right values of dogX and coinX are, so they can't write "automatically"?  I expect there is something automatic to do, but it isn't clear that what they write is automatic.

**Comment by Emmay** [comment]
Related to #110
